const languages = [
  { code: "tr", longCode: "tr-TR", name: "Türkçe" },
  { code: "en", longCode: "en-US", name: "English" },
  { code: "de", longCode: "de-DE", name: "Deutsch" },
  { code: "fr", longCode: "fr-FR", name: "Français" },
  { code: "es", longCode: "es-ES", name: "Español" },
  { code: "it", longCode: "it-IT", name: "Italiano" },
  { code: "ru", longCode: "ru-RU", name: "Русский" },
  { code: "ar", longCode: "ar-AR", name: "العربية" },
  { code: "zh", longCode: "zh-ZH", name: "中文" },
  { code: "ja", longCode: "ja-JA", name: "日本語" },
  { code: "ko", longCode: "ko-KO", name: "한국어" },
  { code: "pt", longCode: "pt-PT", name: "Português" },
  { code: "hi", longCode: "hi-IN", name: "हिन्दी" },
  { code: "nl", longCode: "nl-NL", name: "Nederlands" },
  { code: "sv", longCode: "sv-SE", name: "Svenska" },
];
